version: "3.9" # optional since v1.27.0
services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
