version: "3.8"
services:
  db:
    build:
      context: ./docker
      dockerfile: timescaledb-Dockerfile
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
