name: Nautic Net Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MIX_ENV: test
  ImageOS: ubuntu20
  NETCDF_BUILD: true

permissions:
  contents: read

jobs:
  build:

    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nautic_net_web_test
        image: timescale/timescaledb-ha:pg14-latest
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.14.2'
        otp-version: '25.0.2'
    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: '1.66.1'
    - name: Install NetCDF dependencies
      run: sudo apt install libhdf5-serial-dev libnetcdf-dev
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile Code
      run:  mix compile --warnings-as-errors
    - name: Format Code
      run:  mix format --check-formatted
    - name: Check for retired deps
      run:  mix hex.audit
    - name: Scan for security vulnerabilities on deps
      run:  mix deps.audit
    - name: Run security-focused static analysis (ignoring HTTPS until automatic deployment)
      run:  mix sobelow -i Config.HTTPS